- app/Http/Controllers/Goods/GoodController.php
- app/Http/Controllers/JWTAuthController.php
- app/Http/Controllers/RegisterUserController.php
- app/Http/Controllers/Reptiles/ReptileController.php
- app/Http/Kernel.php
- app/Http/Middleware/CorsMiddleware.php
- app/Http/Requests/LoginUserRequest.php
- app/Http/Requests/RegisterUserRequest.php
- routes/api.php
- 회원가입 및 로그인 유효성 검사 예외처리
- Kernel.php 미들웨어 등록
> 🔨 chore : CorsMeddlewareの設定とException処理

- app/Http/Controllers/ForgetPasswordController.php
- app/Http/Controllers/JWTAuthController.php
- app/Http/Controllers/RegisterUserController.php
- app/Http/Controllers/Reptiles/ReptileController.php
- app/Http/Middleware/JWTMiddleware.php
- app/Http/Requests/RegisterUserRequest.php
- app/Http/Requests/ReptileRequest.php
- routes/api.php
- 파충류 정보 등록, 수정, 삭제 기능 완료
- 파충류 등록일 기준으로 age 변경
> ✨ feat : reptile登録機能の開発完了

- app/Http/Controllers/ForgetPasswordController.php
- app/Http/Controllers/JWTAuthController.php
- app/Http/Controllers/RegisterUserController.php
- app/Http/Controllers/Reptiles/CageController.php
- app/Http/Controllers/Reptiles/ReptileController.php
- app/Http/Middleware/JWTMiddleware.php
- app/Mail/OrderShipped.php
- app/Models/Cage.php
- database/migrations/2024_02_21_083703_create_cages_table.php
- routes/api.php
- 사육장 CRUD 기능 완료
- response 메세지 수정
> ✨ feat : cage登録機能の開発完了

- app/Http/Kernel.php
- app/Http/Middleware/JWTMiddleware.php
> 🐛 fix : CORSバグの修正1

- app/Http/Controllers/ForgetPasswordController.php
- app/Http/Controllers/RegisterUserController.php
- app/Http/Controllers/Reptiles/CageController.php
- app/Http/Controllers/Reptiles/ReptileController.php
- app/Http/Kernel.php
- app/Http/Middleware/CorsMiddleware.php
- routes/api.php
- CorsMiddleware.php 사용안함 : laravel 기본 설정 사용
> 🐛 fix : CORSバグの修正2

- resources/views/mail/orders/shipped.blade.php
> 🔨 chore : mail authCodeの修正

- app/Http/Controllers/ForgetPasswordController.php
> 🔨 chore : mail authCodeの修正2

- app/Http/Controllers/ForgetPasswordController.php
> 🔨 chore : 期限切れのauthCodeを削除する機能を追加

- app/Http/Controllers/ForgetPasswordController.php
- composer.json
- composer.lock
- docker-compose.yml
- nginx.conf
> 👷 build : redis設置

- app/Http/Controllers/ForgetPasswordController.php
- app/Jobs/SendEmailJob.php
- database/factories/GoodFactory.php
- docker-compose.yml
- nginx.conf
- Email 발송 지연 시간 단축을 위해 비동기로 전환
> ✨ feat : mail送信を非同期に切り替え

- app/Http/Controllers/ForgetPasswordController.php
- app/Http/Requests/LoginUserRequest.php
- app/Http/Requests/RegisterUserRequest.php
> 🔨 chore : mail送信コードの修正

- app/Http/Controllers/Boards/CommentController.php
- app/Http/Controllers/Boards/PostController.php
- app/Http/Controllers/Goods/GoodController.php
- app/Http/Controllers/Goods/GoodReviewController.php
- app/Models/GoodReview.php
- good, goodReview, post, comment 컨트롤러 코드 수정
- goodReview 모델 코드 추가
> 🔨 chore : controller 全般的修正

- app/Http/Controllers/ForgetPasswordController.php
- app/Http/Controllers/RegisterUserController.php
- app/Http/Controllers/Reptiles/CageController.php
- app/Http/Controllers/Reptiles/ReptileController.php
- app/Http/Controllers/Sensors/TemperatureHumidityController.php
- app/Models/Cage.php
- app/Models/CageSerialCode.php
- app/Models/Category.php
- app/Models/Reptile.php
- app/Models/User.php
- app/Models/Video.php
- database/factories/CageSerialCodeFactory.php
- database/factories/GoodFactory.php
- database/migrations/2024_02_21_083201_create_reptiles_table.php
- database/migrations/2024_02_21_083603_create_cage_serial_codes_table.php
- database/migrations/2024_02_21_083703_create_cages_table.php
- database/migrations/2024_02_21_101513_create_temperature_humidities_table.php
- database/migrations/2024_02_21_102213_create_videos_table.php
- database/migrations/2024_04_03_103241_create_categories_table.php
- database/seeders/CategorySeeder.php
- database/seeders/DatabaseSeeder.php
- routes/api.php
- cage 시리얼코드 factory 생성
- category seeder 생성
- 마이그레이션 파일 수정
> ✨ feat : cage 温・湿度センサーのデータ保存機能実装

- app/Http/Controllers/Upload/ImageController.php
- database/seeders/UserSeeder.php
- 관리지 이메일 변경(실제 구글계정)
- 이미지 업로드 관련 코드 수정(버킷설정)
- 이미지 업로드, 삭제 기능 추가
> 🔨 chore : 管理者メールの修正

- app/Http/Controllers/JWTAuthController.php
- app/Http/Controllers/Reptiles/ReptileController.php
- app/Http/Controllers/Upload/ImageController.php
- app/Http/Middleware/JWTMiddleware.php
- app/Http/Requests/ReptileRequest.php
- app/Mail/OrderShipped.php
- app/Models/Cage.php
- app/Models/Good.php
- app/Models/Post.php
- app/Models/Reptile.php
- database/factories/CageSerialCodeFactory.php
- database/migrations/2024_02_21_083201_create_reptiles_table.php
- database/migrations/2024_02_21_083703_create_cages_table.php
- database/migrations/2024_03_07_081056_create_moulting_cycles_table.php
- 토큰 응답헤더에 저장
- 파충류 등록 시 이미지 저장 추가
> 🔨 chore : reptiles 機能の修正

- app/Http/Controllers/Boards/PostController.php
- app/Http/Controllers/Goods/GoodController.php
- app/Models/Post.php
- PostController, GoodController
- Good.php (model)
> 🔨 chore : controller, model 修整

- app/Http/Controllers/Reptiles/CageController.php
- app/Models/Cage.php
- app/Models/Category.php
- config/cors.php
- database/migrations/2024_02_21_071900_create_categories_table.php
- database/migrations/2024_02_21_083703_create_cages_table.php
- database/seeders/CategorySeeder.php
- 마켓 카테고리 기본 이미지 등록
- 토큰인증 cors.php 파일 수정
> 🔨 chore : 爬虫類、ケージに画像追加機能製作中

- app/Http/Controllers/Reptiles/CageController.php
- app/Http/Controllers/Reptiles/ReptileController.php
- app/Http/Controllers/Sensors/TemperatureHumidityController.php
- app/Http/Requests/ReptileRequest.php
- routes/api.php
- 파충류, 케이지 이미지 수정 기능 추가
- 사육장 온습도 센서 데이터 조회 기능 추가
> 🔨 chore : 爬虫類、ケージの画像修正機能を追加

- routes/api.php
selectCategory 컨트롤러 변경
CategoryController -> PostController
> 🔨 chore : コントローラー住所変更

- app/Http/Controllers/Boards/PostController.php
컬럼명 수정
category -> category_id
> 🔨 chore : カラム名修正

- app/Http/Controllers/Boards/PostController.php
> 🔨 chore : 親カテゴリのID情報追加

- app/Http/Controllers/Boards/PostController.php
> 🔨 chore : 衝突解決

- app/Http/Controllers/JWTAuthController.php
- app/Http/Controllers/Reptiles/CageController.php
- app/Http/Controllers/Reptiles/ReptileController.php
- app/Http/Controllers/Sensors/TemperatureHumidityController.php
- database/migrations/2024_02_21_083201_create_reptiles_table.php
- database/migrations/2024_02_21_083703_create_cages_table.php
- routes/api.php
- 파충류 닉네임 속성을 이름 속성으로 변경
- 케이지 이름 속성 추가
- 로그인 refresh 토큰 발급 api 추가, 현재 주석처리
> 🧹 chore: cage, reptile登録validationの修正

- app/Http/Controllers/Reptiles/CageController.php
- app/Http/Middleware/JWTMiddleware.php
- routes/api.php
- refresh token 재발급 api 작성
- 온, 습도 기록 api요청을 get으로 변경
> 🧹 chore: refresh token再発行apiの作成

- app/Http/Controllers/Boards/PostController.php
의존성 주입이 되어있기 때문에 Post 모델을 사용안해도 된다고 판단
> 🔨 chore : Dependency修正

- app/Http/Controllers/Boards/PostController.php
- app/Http/Controllers/Boards/SupportController.php
- app/Http/Controllers/Goods/PurchaseController.php
- routes/api.php
- SupportController store, show, update, destroy, answer 追加
- PurchaseController コード修正
> ✨ feat : SupportController 及び PurchaseController 機能追加

- database/migrations/2024_02_21_072910_create_comments_table.php
> 🔨 chore : カラム属性変更

- app/Http/Controllers/Boards/PostController.php
- 게시글 페이지네이션 추가
- 카테고리별 글 반환값 추가 (댓글)
> ✨ feat : ページネーション技能追加

- app/Http/Controllers/Boards/PostController.php
> 🔨 chore : ユーザーネームを返すように変更
